accounts/urls.py
from django.urls import path

from .views import ProfileUser, SignUp, signup_mail_sent_view, ConfirmationSignUp


urlpatterns = [
    path('<int:pk>/profile/', ProfileUser.as_view(), name='profile_user'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('signup_mail_sent/', signup_mail_sent_view, name='signup_mail_sent'),
    path('<int:pk>/confirmation_signup/', ConfirmationSignUp.as_view(), name='confirmation_signup'),
]

prjboard/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from ckeditor_uploader.views import upload, browse
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon/favicon.ico', RedirectView.as_view()),
    path('board/', include('appboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/browse/', login_required(browse), name='ckeditor_browse'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appboard/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from crum import get_current_user
from django.urls import reverse

from .utils import get_text_from_html


class Post(models.Model):
    CATEGORIES = [
        ('TA', 'Танки'),
        ('HL', 'Хилы'),
        ('DD', 'ДД'),
        ('TR', 'Торговцы'),
        ('GM', 'Гилдмастеры'),
        ('QG', 'Квестгиверы'),
        ('SM', 'Кузнецы'),
        ('TN', 'Кожевники'),
        ('PT', 'Зельевары'),
        ('SP', 'Мастера заклинаний'),
    ]

    title = models.CharField('Объявление', max_length=64)
    content = RichTextUploadingField('Содержание')
    category = models.CharField('Категория', max_length=2, choices=CATEGORIES, default='TA')
    time_in = models.DateTimeField(auto_now_add=True)
    preview = models.CharField(max_length=64, blank=True, null=True, default=None)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
        self.preview = get_text_from_html(self.content)
        super().save(*args, **kwargs)

    def get_title(self):
        return str(self.title).upper()

    def __str__(self):
        return f'{self.get_title()}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])

    def date_in(self):
        return self.time_in.date()


class Reply(models.Model):
    STATUSES = [
        ('C', 'Создан'),
        ('A', 'Принят'),
        ('D', 'Отклонен'),
    ]

    text = models.CharField('Отклик', max_length=128)
    status = models.CharField('Статус', max_length=1, choices=STATUSES, default='C')
    time_in = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reply', editable=False,
                             blank=True, null=True, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
            if kwargs.get('pk') and not self.post:
                pk = int(kwargs['pk'])
                self.post = Post.objects.get(pk=pk)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.text}'

    def date_in(self):
        return self.time_in.date()


class News(models.Model):
    title = models.CharField('Новость', max_length=64)
    text = models.CharField('Текст', max_length=128, default='In progress', help_text='preview_text')
    content = RichTextUploadingField('Содержание')
    time_in = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if not self.pk:
            self.author = user
        super().save(*args, **kwargs)

    def get_title(self):
        return str(self.title).upper()

    def __str__(self):
        return f'{self.get_title()}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.pk)])

    def preview(self):
        return f'{self.text[:64]}...'

    def date_in(self):
        return self.time_in.date()

templates/default.html
<!DOCTYPE html>
{% load static %}


<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>
            {% block title %}
            {% endblock title %}
        </title>

        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="shortcut icon" href="{%  static 'favicon/favicon.ico' %}"/>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="/admin/">Доска Объявлений</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/board/pass/">Hi!</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/board/news/">Новости</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/board/posts/">Объявления</a>
                        </li>
                        {% if perms.appboard.add_post %}
                        <li class="nav-item">
                            <a class="nav-link" href="/board/post_create">Новое объявление</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="nav-right">
                    <ul class="navbar-nav ml-auto">
                        {% if user.is_active and user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'replies_to_author' %}">Отклики</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'profile_user' pk=user.id %}">
                                    Профиль {{ user.username }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/logout/">Выход</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/login/">Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/accounts/signup/">Регистрация</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    {% block content %}
                    {% endblock content %}
                </div>
            </div>
        </div>
    </body>
</html>