accounts/urls.py
from django.urls import path

from .views import ProfileUser, SignUp, signup_mail_sent_view, ConfirmationSignUp


urlpatterns = [
    path('<int:pk>/profile/', ProfileUser.as_view(), name='profile_user'),
    path('signup/', SignUp.as_view(), name='signup'),
    path('signup_mail_sent/', signup_mail_sent_view, name='signup_mail_sent'),
    path('<int:pk>/confirmation_signup/', ConfirmationSignUp.as_view(), name='confirmation_signup'),
]

prjboard/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.conf import settings
from ckeditor_uploader.views import upload, browse
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon/favicon.ico', RedirectView.as_view()),
    path('board/', include('appboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('silk/', include('silk.urls', namespace='silk')),
    path('ckeditor/upload/', login_required(upload), name='ckeditor_upload'),
    path('ckeditor/browse/', login_required(browse), name='ckeditor_browse'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appboard/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from crum import get_current_user
from django.urls import reverse

from .utils import get_text_from_html


class Post(models.Model):
    CATEGORIES = [
        ('TA', 'Танки'),
        ('HL', 'Хилы'),
        ('DD', 'ДД'),
        ('TR', 'Торговцы'),
        ('GM', 'Гилдмастеры'),
        ('QG', 'Квестгиверы'),
        ('SM', 'Кузнецы'),
        ('TN', 'Кожевники'),
        ('PT', 'Зельевары'),
        ('SP', 'Мастера заклинаний'),
    ]

    title = models.CharField('Объявление', max_length=64)
    content = RichTextUploadingField('Содержание')
    category = models.CharField('Категория', max_length=2, choices=CATEGORIES, default='TA')
    time_in = models.DateTimeField(auto_now_add=True)
    preview = models.CharField(max_length=64, blank=True, null=True, default=None)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
        self.preview = get_text_from_html(self.content)
        super().save(*args, **kwargs)

    def get_title(self):
        return str(self.title).upper()

    def __str__(self):
        return f'{self.get_title()}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.pk)])

    def date_in(self):
        return self.time_in.date()


class Reply(models.Model):
    STATUSES = [
        ('C', 'Создан'),
        ('A', 'Принят'),
        ('D', 'Отклонен'),
    ]

    text = models.CharField('Отклик', max_length=128)
    status = models.CharField('Статус', max_length=1, choices=STATUSES, default='C')
    time_in = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='reply', editable=False,
                             blank=True, null=True, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        if not self.pk:
            user = get_current_user()
            self.author = user
            if kwargs.get('pk') and not self.post:
                pk = int(kwargs['pk'])
                self.post = Post.objects.get(pk=pk)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.text}'

    def date_in(self):
        return self.time_in.date()


class News(models.Model):
    title = models.CharField('Новость', max_length=64)
    text = models.CharField('Текст', max_length=128, default='In progress', help_text='preview_text')
    content = RichTextUploadingField('Содержание')
    time_in = models.DateTimeField(auto_now_add=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='news', editable=False,
                               blank=True, null=True, default=None)

    def save(self, *args, **kwargs):
        user = get_current_user()
        if not self.pk:
            self.author = user
        super().save(*args, **kwargs)

    def get_title(self):
        return str(self.title).upper()

    def __str__(self):
        return f'{self.get_title()}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.pk)])

    def preview(self):
        return f'{self.text[:64]}...'

    def date_in(self):
        return self.time_in.date()

templates/board/news_detail.html
{% extends 'default.html' %}

{% block title %}
News {{ new.pk }}
{% endblock title %}
 
{% block content %}
    <h4>Новость {{ new.pk }}</h4>
    <hr>
    <p>&nbsp;</p>
    <h3>{{ new }}</h3>
    <h6>{{ new.time_in|date:'d M Y l' }}</h6>
    <p>&nbsp;</p>
    <p><em>{{ new.text }}</em></p>
    <p>{{ new.content|safe }}</p>
    <p>_____</p>
{% endblock content %}

templates/board/news_list.html
{% extends 'default.html' %}

{% load custom_tags %}

{% block title %}
News
{% endblock title %}
 
{% block content %}
    <h4>Новости</h4>
    <h6>показано {{ news|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if news %}
        <center><table>
            <tr>
                <td>Новость</td>
                <td>&emsp;</td>
                <td>Превью</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
            </tr>
            {% for new in news %}
            <tr>
                <td><a href="{{ new.id }}">{{ new.title|upper }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ new.id }}">{{ new.preview }}</a></td>
                <td>&emsp;</td>
                <td>{{ new.time_in|date:'M d Y' }}</td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Отсутствие новостей - хорошая новость!</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}

templates/board/news_send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Send news {{ news_list }}</title>
</head>
<body>
    {% for new in news %}
        <h4>Новость {{ new.pk }}</h4>
        <p>***</p>
        <h3>{{ new }}</h3>
        <h5>{{ new.time_in|date:'d M Y l' }}</h5>
        <br>
        <p><em>{{ new.text }}</em></p>
        <h5><em><a href="{{ link }}{{ new.pk }}/">Для просмотра полной новости пройдите по ссылке</a></em></h5>
        <p>***</p>
        <hr><br>
    {% endfor %}
</body>
</html>

templates/board/pass.html
{% extends "default.html" %}

{% block title %}
Hi!
{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        <p>&nbsp;</p>
        <h4>{{ user.username }}, вы авторизованы!</h4>
        <hr>
        <p>&nbsp;</p>
        <a href="{% url 'profile_user' pk=user.id %}">Ваш профиль</a>
    {% else %}
        <p></p>
        <h4>Не залогинен</h4>
        <hr>
    {% endif %}
{% endblock content %}

templates/board/post.html
{% extends 'default.html' %}

{% block title %}
Post {{ post.pk }}
{% endblock title %}
 
{% block content %}
    <h3>{{ post.author }}</h3>
    <h4>Объявление {{ post.pk }}</h4>
    <hr>
    <p>&nbsp;</p>
    <h4>{{ post.get_category_display }}</h4>
    <h3>{{ post }}</h3>
    <h6>{{ post.time_in|date:'d M Y l' }}</h6>
    <p>&nbsp;</p>
    <p>{{ post.content|safe }}</p>
    {% if perms.appboard.change_post and user == post.author %}
        <p>_____</p>
        <a href="{% url 'post_update' pk=post.pk %}">
        <input type="submit" class="mt-3 btn-primary" value="Редактировать" /></a>
    {% elif user.is_authenticated %}
        <hr>
        <p>&nbsp;</p>
        <form action="{% url 'reply_create' pk=post.pk %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="hidden" name="pk" id="pk" value="{{ post.pk }}">
            <p><label for="reply_text">Написать отклик:</label></p>
            <p><input type="text" name="text" maxlength="128" required="" id="reply_text" size="128"></p>
            <p><input type="submit" class="mt-3 btn-primary" value="Сохранить" /></p>
        </form>
        <p>_____</p>

        {% if replies %}
            <h4>Ваши отклики на это объявление</h4>
            <br>
            <center><table>
                <tr>
                    <td>Отклик</td>
                    <td>&emsp;</td>
                    <td>Статус</td>
                    <td>&emsp;</td>
                    <td>Написан</td>
                </tr>
                {% for reply in replies %}
                <tr>
                    <td>{{ reply.text }}</td>
                    <td>&emsp;</td>
                    <td>{{ reply.get_status_display }}</a></td>
                    <td>&emsp;</td>
                    <td>{{ reply.time_in|date:'M d Y' }}</td>
                </tr>
                {% endfor %}
            </table></center>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/board/post_edit.html
{% extends 'default.html' %}

{% block title %}
Post edit {{ post.pk }}
{% endblock title %}
 
{% block content %}
    {% if post.pk %}
        <h4>Редактирование объявления {{ post.pk }}</h4>
    {% else %}
        <h4>Новое объявление</h4>
    {% endif %}
    <hr>
    <p>&nbsp;</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit" class="mt-3 btn-primary" value="Сохранить" />
    </form>
    <p>_____</p>
{% endblock content %}

templates/board/posts.html
{% extends 'default.html' %}

{% load custom_tags %}

{% block title %}
Posts
{% endblock title %}
 
{% block content %}
    <h4>Объявления</h4>
    <h6>показано {{ posts|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if posts %}
        <center><table>
            <tr>
                <td>Объявление</td>
                <td>&emsp;</td>
                <td>Категория</td>
                <td>&emsp;</td>
                <td>Автор</td>
                <td>&emsp;</td>
                <td>Содержание</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
            </tr>
            {% for post in posts %}
            <tr>
                <td><a href="{{ post.pk }}">{{ post.title|upper }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ post.pk }}">{{ post.get_category_display }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ post.pk }}">{{ post.author }}</a></td>
                <td>&emsp;</td>
                <td><a href="{{ post.pk }}">{{ post.preview }}</a></td>
                <td>&emsp;</td>
                <td>{{ post.time_in|date:'M d Y' }}</td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Отсутствие объявлений - это вообще не новость!</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}

templates/board/replies_list.html
{% extends 'default.html' %}

{% load custom_tags %}

{% block title %}
Replies to author
{% endblock title %}
 
{% block content %}
    <h4>Отклики на мои объявления</h4>
    <h6>показано {{ replies|length }} из {{ paginator.count }}</h6>
    <hr>
    {% if replies %}
        <center><table>
            <tr>
                <td>Объявление</td>
                <td>&emsp;</td>
                <td>Категория</td>
                <td>&emsp;</td>
                <td>Опубликовано</td>
                <td>&emsp;</td>
                <td>Отклик</td>
                <td>&emsp;</td>
                <td>Статус</td>
                <td>&emsp;</td>
                <td>Автор</td>
                <td>&emsp;</td>
                <td>Отправлен</td>
                <td>&emsp;</td>
                <td>Действие</td>
            {% for reply in replies %}
            <tr>
                <td valign="bottom"><a href="/board/posts/{{ reply.post.id }}">{{ reply.post }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom"><a href="/board/posts/{{ reply.post.id }}">{{ reply.post.get_category_display }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom"><a href="/board/posts/{{ reply.post.id }}">{{ reply.post.time_in|date:'M d Y' }}</a></td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.get_status_display }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.author }}</td>
                <td>&emsp;</td>
                <td valign="bottom">{{ reply.time_in|date:'M d Y' }}</td>
                <td>&emsp;</td>
                <td valign="top">
                {% if reply.status == 'C' %}
                    <form action="{% url 'reply_set_status' %}?next={{ request.get_full_path }}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="pk" id="pk" value={{ reply.pk }}>
                        <input type="submit" class="mt-3 btn-primary" name="accept" value="Принять" />
                        <input type="submit" class="mt-3 btn-primary" name="reject" value="Отклонить" />
                    </form>
                {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table></center>
    {% else %}
        <h6>Нет откликов</h6>
    {% endif %}
    <p>&nbsp;</p>
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            {% if page_obj.previous_page_number != 2 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            {% if paginator.num_pages != page_obj.next_page_number|add:1 %}
                ...
            {% endif %}
            <a href="?{% url_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
    <hr>
    <form action="" method="get">
            {% csrf_token %}
            {{ filterset.form.as_p }}
            <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>
{% endblock content %}